server:
  port: ${LOCAL_SERVER_PORT}

spring:
  application:
    name: config-server
  config:
    activate:
      on-profile: default
  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_REPO_URI}
          default-label: ${GITHUB_BRANCH}
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_LOCAL_IP_ADDRESS}
    port: ${RABBITMQ_LOCAL_PORT}
    username: ${RABBITMQ_LOCAL_USERNAME}
    password: ${RABBITMQ_LOCAL_PASSWORD}

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_LOCAL_SERVER_IP_ADDRESS}

management:
  endpoints:
    web:
      exposure:
        include: ${SPRING_ACTUATOR_MANAGEMENT}