server:
  port: ${PROD_SERVER_PORT}

spring:
  application:
    name: config-server
  config:
    activate:
      on-profile: prod
  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_REPO_URI}
          default-label: ${GITHUB_BRANCH}
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_IP_PROD_ADDRESS}
    port: ${RABBITMQ_PROD_PORT}
    username: ${RABBIMT_PROD_USERNAME}
    password: ${RABBIMT_PROD_PASSWORD}

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${PROD_EUREKA_SERVER_URL}/eureka

management:
  endpoints:
    web:
      exposure:
        include: ${SPRING_ACTUATOR_MANAGEMENT}