server:
  port: 8080
  servlet:
    encoding:
      force-response: true
      enabled: true
      force: true
      charset: UTF-8

kafka:
  topic:
    member:
      updateinfo: dev-member-updateinfo

spring:
  # KAFKA
  kafka:
    #bootstrap-servers: 70.12.247.83:9092
    bootstrap-servers: localhost:9092
  # MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/message?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        format_sql: true

  # Swagger
  mvc:
  pathmatch:
    matching-strategy: ant_path_matcher

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE