server:
  port: 8081
spring:
  server:
    servlet:
      encoding:
        force-response: true
  output:
    ansi:
      enabled: always
  kafka:
    bootstrap-servers: localhost:9092

message:
  topic:
    name: ${TOPIC_NAME}
    group-id: member

data:
  redis:
    host: localhost
    port: 6379